# Generated by Django 4.2.7 on 2025-04-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0004_auto_create_turf_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
