# Generated by Django 4.2.7 on 2025-04-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfbooked',
            name='is_dummy_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turfbooked',
            name='payment_method',
            field=models.CharField(default='credit_card', max_length=50),
        ),
    ]
