# Generated by Django 4.2.7 on 2025-04-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0002_turfbooked_is_dummy_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='The SK Sports Turf', max_length=200)),
                ('slot_price', models.IntegerField(default=500)),
                ('description', models.TextField(default='The best sports turf in town')),
                ('address', models.TextField(default='')),
                ('contact_phone', models.CharField(default='', max_length=20)),
                ('contact_email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
