# Generated by Django 4.2.7 on 2025-04-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0005_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
